### PR TITLE
I added content to README.md file

### PR DESCRIPTION
**Pull request by MohammedC4r**

### CODE REVIEW

**Comment by MohammedChaker** [comment]
# boss
It really nice i will accept

**Comment by MohammedChaker** [comment]
wait you wrote "really" with one "l"

**Comment by MohammedC4r** [comment]
Sorry sir, i realy sorry

**Comment by MohammedC4r** [comment]
I realy sorry

**Comment by MohammedC4r** [comment]
I will fix it right now..

**Comment by MohammedChaker** [comment]
you can sleep..

**Pull request merged**
